/**
 * Global football club logo registry
 * Uses api-sports.io media CDN (publicly accessible PNG files)
 * URL format: https://media.api-sports.io/football/teams/{id}.png
 *
 * Covers all 20 Premier League clubs, all 20 La Liga clubs,
 * all 18 Bundesliga clubs, all 20 Serie A clubs, all 18 Ligue 1 clubs,
 * Eredivisie, Primeira Liga, UCL/UEL regulars, and other major clubs.
 */

const CDN = "https://media.api-sports.io/football/teams";

const logo = (id: number) => `${CDN}/${id}.png`;

// ─── Premier League ───────────────────────────────────────────────
const PREMIER_LEAGUE: Record<string, string> = {
  "Arsenal": logo(42),
  "Aston Villa": logo(66),
  "Bournemouth": logo(35),
  "Brentford": logo(55),
  "Brighton": logo(51),
  "Brighton & Hove Albion": logo(51),
  "Chelsea": logo(49),
  "Crystal Palace": logo(52),
  "Everton": logo(45),
  "Fulham": logo(36),
  "Ipswich": logo(57),
  "Ipswich Town": logo(57),
  "Leicester": logo(46),
  "Leicester City": logo(46),
  "Liverpool": logo(40),
  "Man City": logo(50),
  "Manchester City": logo(50),
  "Man Utd": logo(33),
  "Manchester United": logo(33),
  "Newcastle": logo(34),
  "Newcastle United": logo(34),
  "Nottm Forest": logo(65),
  "Nottingham Forest": logo(65),
  "Southampton": logo(41),
  "Tottenham": logo(47),
  "Tottenham Hotspur": logo(47),
  "West Ham": logo(48),
  "West Ham United": logo(48),
  "Wolves": logo(39),
  "Wolverhampton": logo(39),
  "Sunderland": logo(69),
  "Leeds": logo(63),
  "Leeds United": logo(63),
  "Burnley": logo(44),
  "Sheffield United": logo(62),
  "Luton": logo(1359),
  "Luton Town": logo(1359),
  "Watford": logo(38),
  "Norwich": logo(71),
  "Norwich City": logo(71),
  "Middlesbrough": logo(68),
  "Stoke": logo(70),
  "Stoke City": logo(70),
  "Swansea": logo(72),
  "Swansea City": logo(72),
  "Cardiff": logo(60),
  "Cardiff City": logo(60),
  "Hull": logo(64),
  "Hull City": logo(64),
  "QPR": logo(67),
};

// ─── La Liga ──────────────────────────────────────────────────────
const LA_LIGA: Record<string, string> = {
  "Alaves": logo(723),
  "Deportivo Alaves": logo(723),
  "Athletic": logo(531),
  "Athletic Bilbao": logo(531),
  "Athletic Club": logo(531),
  "Atletico": logo(530),
  "Atletico Madrid": logo(530),
  "Atlético Madrid": logo(530),
  "Barcelona": logo(529),
  "FC Barcelona": logo(529),
  "Betis": logo(543),
  "Real Betis": logo(543),
  "Celta": logo(538),
  "Celta Vigo": logo(538),
  "Espanyol": logo(532),
  "RCD Espanyol": logo(532),
  "Getafe": logo(546),
  "Girona": logo(547),
  "Las Palmas": logo(724),
  "UD Las Palmas": logo(724),
  "Leganes": logo(725),
  "CD Leganés": logo(725),
  "Mallorca": logo(798),
  "RCD Mallorca": logo(798),
  "Osasuna": logo(727),
  "CA Osasuna": logo(727),
  "Rayo": logo(726),
  "Rayo Vallecano": logo(726),
  "Real Madrid": logo(541),
  "Real Sociedad": logo(548),
  "Sevilla": logo(536),
  "Sevilla FC": logo(536),
  "Valencia": logo(532),
  "Valencia CF": logo(532),
  "Valladolid": logo(729),
  "Real Valladolid": logo(729),
  "Villarreal": logo(533),
  "Villarreal CF": logo(533),
};

// ─── Bundesliga ───────────────────────────────────────────────────
const BUNDESLIGA: Record<string, string> = {
  "Augsburg": logo(170),
  "FC Augsburg": logo(170),
  "Bayer Leverkusen": logo(168),
  "Leverkusen": logo(168),
  "Bayern": logo(157),
  "Bayern Munich": logo(157),
  "FC Bayern": logo(157),
  "FC Bayern München": logo(157),
  "Bochum": logo(171),
  "VfL Bochum": logo(171),
  "Dortmund": logo(165),
  "Borussia Dortmund": logo(165),
  "BVB": logo(165),
  "Gladbach": logo(163),
  "Borussia Mönchengladbach": logo(163),
  "Mönchengladbach": logo(163),
  "Eintracht Frankfurt": logo(169),
  "Frankfurt": logo(169),
  "Freiburg": logo(172),
  "SC Freiburg": logo(172),
  "Heidenheim": logo(176),
  "1. FC Heidenheim": logo(176),
  "Hoffenheim": logo(167),
  "TSG Hoffenheim": logo(167),
  "Holstein Kiel": logo(177),
  "Kiel": logo(177),
  "Mainz": logo(164),
  "1. FSV Mainz 05": logo(164),
  "RB Leipzig": logo(173),
  "Leipzig": logo(173),
  "St. Pauli": logo(178),
  "FC St. Pauli": logo(178),
  "Stuttgart": logo(162),
  "VfB Stuttgart": logo(162),
  "Union Berlin": logo(174),
  "1. FC Union Berlin": logo(174),
  "Werder": logo(161),
  "Werder Bremen": logo(161),
  "Wolfsburg": logo(158),
  "VfL Wolfsburg": logo(158),
  "Schalke": logo(159),
  "FC Schalke 04": logo(159),
  "Hertha": logo(160),
  "Hertha Berlin": logo(160),
  "Hamburger SV": logo(166),
  "Hamburg": logo(166),
  "Kaiserslautern": logo(179),
};

// ─── Serie A ──────────────────────────────────────────────────────
const SERIE_A: Record<string, string> = {
  "AC Milan": logo(489),
  "Milan": logo(489),
  "Atalanta": logo(499),
  "Bologna": logo(500),
  "Cagliari": logo(488),
  "Como": logo(501),
  "Como 1907": logo(501),
  "Empoli": logo(511),
  "Fiorentina": logo(502),
  "Genoa": logo(495),
  "Genoa CFC": logo(495),
  "Hellas Verona": logo(504),
  "Verona": logo(504),
  "Inter": logo(505),
  "Inter Milan": logo(505),
  "Internazionale": logo(505),
  "FC Internazionale": logo(505),
  "Juventus": logo(496),
  "Juve": logo(496),
  "Lazio": logo(487),
  "SS Lazio": logo(487),
  "Lecce": logo(867),
  "US Lecce": logo(867),
  "Monza": logo(1579),
  "AC Monza": logo(1579),
  "Napoli": logo(492),
  "SSC Napoli": logo(492),
  "Parma": logo(512),
  "Parma Calcio": logo(512),
  "Roma": logo(497),
  "AS Roma": logo(497),
  "Torino": logo(503),
  "Torino FC": logo(503),
  "Udinese": logo(494),
  "Udinese Calcio": logo(494),
  "Venezia": logo(517),
  "Venezia FC": logo(517),
  "Salernitana": logo(514),
  "Frosinone": logo(513),
  "Cremonese": logo(510),
};

// ─── Ligue 1 ──────────────────────────────────────────────────────
const LIGUE_1: Record<string, string> = {
  "Angers": logo(94),
  "SCO Angers": logo(94),
  "Auxerre": logo(106),
  "AJ Auxerre": logo(106),
  "Brest": logo(130),
  "Stade Brestois": logo(130),
  "Le Havre": logo(1093),
  "HAC": logo(1093),
  "Lens": logo(116),
  "RC Lens": logo(116),
  "Lille": logo(79),
  "LOSC Lille": logo(79),
  "Lyon": logo(80),
  "Olympique Lyonnais": logo(80),
  "OL": logo(80),
  "Marseille": logo(81),
  "Olympique de Marseille": logo(81),
  "OM": logo(81),
  "Monaco": logo(91),
  "AS Monaco": logo(91),
  "Montpellier": logo(82),
  "Montpellier HSC": logo(82),
  "Nantes": logo(83),
  "FC Nantes": logo(83),
  "Nice": logo(84),
  "OGC Nice": logo(84),
  "PSG": logo(85),
  "Paris Saint-Germain": logo(85),
  "Paris SG": logo(85),
  "Rennes": logo(111),
  "Stade Rennais": logo(111),
  "Reims": logo(108),
  "Stade de Reims": logo(108),
  "Saint-Etienne": logo(87),
  "AS Saint-Etienne": logo(87),
  "Strasbourg": logo(95),
  "RC Strasbourg": logo(95),
  "Toulouse": logo(96),
  "Toulouse FC": logo(96),
  "Metz": logo(97),
  "FC Metz": logo(97),
  "Lorient": logo(115),
  "FC Lorient": logo(115),
  "Clermont": logo(514),
};

// ─── Eredivisie ───────────────────────────────────────────────────
const EREDIVISIE: Record<string, string> = {
  "Ajax": logo(194),
  "AFC Ajax": logo(194),
  "Feyenoord": logo(197),
  "PSV": logo(201),
  "PSV Eindhoven": logo(201),
  "AZ": logo(195),
  "AZ Alkmaar": logo(195),
  "Utrecht": logo(206),
  "FC Utrecht": logo(206),
  "Twente": logo(202),
  "FC Twente": logo(202),
  "Heerenveen": logo(199),
  "SC Heerenveen": logo(199),
  "Vitesse": logo(203),
  "SBV Vitesse": logo(203),
  "Sparta Rotterdam": logo(207),
  "Groningen": logo(198),
  "FC Groningen": logo(198),
  "NEC": logo(205),
  "NEC Nijmegen": logo(205),
  "Go Ahead Eagles": logo(213),
  "Almere City": logo(212),
  "RKC Waalwijk": logo(211),
};

// ─── Primeira Liga ────────────────────────────────────────────────
const PRIMEIRA_LIGA: Record<string, string> = {
  "Benfica": logo(211),
  "SL Benfica": logo(211),
  "Porto": logo(212),
  "FC Porto": logo(212),
  "Sporting CP": logo(228),
  "Sporting": logo(228),
  "Braga": logo(217),
  "SC Braga": logo(217),
  "Vitoria Guimaraes": logo(233),
  "Boavista": logo(218),
  "Rio Ave": logo(229),
  "Casa Pia": logo(2283),
  "Gil Vicente": logo(2282),
};

// ─── Scottish Premiership ─────────────────────────────────────────
const SCOTTISH: Record<string, string> = {
  "Celtic": logo(248),
  "Rangers": logo(250),
  "Hearts": logo(252),
  "Hibernian": logo(253),
  "Motherwell": logo(254),
  "Aberdeen": logo(249),
  "St Mirren": logo(255),
};

// ─── Turkey ───────────────────────────────────────────────────────
const TURKISH: Record<string, string> = {
  "Galatasaray": logo(645),
  "Fenerbahce": logo(641),
  "Fenerbahçe": logo(641),
  "Besiktas": logo(642),
  "Beşiktaş": logo(642),
  "Trabzonspor": logo(643),
};

// ─── Other European Clubs (UCL/UEL regulars) ──────────────────────
const EUROPEAN: Record<string, string> = {
  "Red Bull Salzburg": logo(322),
  "FC Salzburg": logo(322),
  "Salzburg": logo(322),
  "Shakhtar": logo(633),
  "Shakhtar Donetsk": logo(633),
  "Dynamo Kyiv": logo(634),
  "Club Brugge": logo(256),
  "KV Mechelen": logo(259),
  "Anderlecht": logo(257),
  "Union SG": logo(261),
  "Royal Antwerp": logo(260),
  "Gent": logo(258),
  "Bayer 04": logo(168),
  "Red Star Belgrade": logo(395),
  "Crvena Zvezda": logo(395),
  "Young Boys": logo(335),
  "BSC Young Boys": logo(335),
  "Basel": logo(333),
  "FC Basel": logo(333),
  "Zurich": logo(336),
  "FC Zurich": logo(336),
  "Slavia Prague": logo(382),
  "Sparta Prague": logo(383),
  "Slovan Bratislava": logo(399),
  "Dinamo Zagreb": logo(415),
  "Hajduk Split": logo(416),
  "Rapid Vienna": logo(324),
  "Sturm Graz": logo(325),
  "LASK": logo(326),
  "Panathinaikos": logo(431),
  "Olympiakos": logo(430),
  "AEK Athens": logo(429),
  "PAOK": logo(432),
  "Anderlecht": logo(257),
  "Midtjylland": logo(371),
  "FC Midtjylland": logo(371),
  "Copenhagen": logo(369),
  "FC Copenhagen": logo(369),
  "Brondby": logo(370),
  "Brøndby": logo(370),
  "Molde": logo(357),
  "Rosenborg": logo(358),
  "Malmo": logo(347),
  "Malmö FF": logo(347),
  "AIK": logo(343),
  "HJK Helsinki": logo(303),
  "Qarabag": logo(442),
  "Apoel": logo(436),
  "Ferencvaros": logo(450),
  "Ferencváros": logo(450),
  "Legia Warsaw": logo(388),
  "Lech Poznan": logo(387),
  "Lech Poznań": logo(387),
  "Maccabi Tel Aviv": logo(484),
  "Maccabi Haifa": logo(485),
};

// ─── South American Clubs ─────────────────────────────────────────
const SOUTH_AMERICAN: Record<string, string> = {
  "River Plate": logo(547),
  "Boca Juniors": logo(546),
  "Flamengo": logo(127),
  "Palmeiras": logo(121),
  "Santos": logo(122),
  "São Paulo": logo(118),
  "Sao Paulo": logo(118),
  "Corinthians": logo(125),
  "Grêmio": logo(119),
  "Gremio": logo(119),
  "Internacional": logo(120),
  "Atletico Mineiro": logo(128),
  "Atlético Mineiro": logo(128),
  "Fluminense": logo(126),
  "Botafogo": logo(124),
  "Nacional": logo(553),
  "Peñarol": logo(555),
  "Penharol": logo(555),
  "America": logo(554),
};

// ─── MLS ──────────────────────────────────────────────────────────
const MLS: Record<string, string> = {
  "LA Galaxy": logo(1605),
  "Los Angeles FC": logo(1607),
  "LAFC": logo(1607),
  "Inter Miami": logo(1596),
  "Inter Miami CF": logo(1596),
  "New York City FC": logo(1608),
  "NYCFC": logo(1608),
  "New York Red Bulls": logo(1609),
  "Seattle Sounders": logo(1609),
  "Portland Timbers": logo(1611),
  "Atlanta United": logo(1612),
  "Toronto FC": logo(1613),
  "CF Montreal": logo(1614),
  "Chicago Fire": logo(1615),
  "Columbus Crew": logo(1616),
  "Philadelphia Union": logo(1617),
  "DC United": logo(1618),
  "New England Revolution": logo(1619),
  "Real Salt Lake": logo(1620),
  "Colorado Rapids": logo(1621),
  "FC Dallas": logo(1622),
  "Sporting Kansas City": logo(1623),
  "Houston Dynamo": logo(1624),
  "Vancouver Whitecaps": logo(1625),
};

// ─── Global fallback registry ─────────────────────────────────────
export const TEAM_LOGO_REGISTRY: Record<string, string> = {
  ...PREMIER_LEAGUE,
  ...LA_LIGA,
  ...BUNDESLIGA,
  ...SERIE_A,
  ...LIGUE_1,
  ...EREDIVISIE,
  ...PRIMEIRA_LIGA,
  ...SCOTTISH,
  ...TURKISH,
  ...EUROPEAN,
  ...SOUTH_AMERICAN,
  ...MLS,
};

/**
 * Look up a team logo URL by name.
 * Tries exact match first, then case-insensitive, then partial match.
 * Returns null if no logo is found (TeamAvatar will show color badge fallback).
 */
export function getTeamLogoUrl(teamName: string): string | null {
  if (!teamName) return null;

  // 1. Exact match
  if (TEAM_LOGO_REGISTRY[teamName]) return TEAM_LOGO_REGISTRY[teamName];

  const lower = teamName.toLowerCase();

  // 2. Case-insensitive exact match
  for (const key of Object.keys(TEAM_LOGO_REGISTRY)) {
    if (key.toLowerCase() === lower) return TEAM_LOGO_REGISTRY[key];
  }

  // 3. Partial match — team name contains key or key contains team name
  for (const key of Object.keys(TEAM_LOGO_REGISTRY)) {
    const k = key.toLowerCase();
    if (lower.includes(k) || k.includes(lower)) {
      return TEAM_LOGO_REGISTRY[key];
    }
  }

  return null;
}
